/**
* This file and any referenced files were automatically generated by @hyperweb/telescope@latest
* DO NOT MODIFY BY HAND. Instead, download the latest proto files for your chain
* and run the transpile command or npm scripts command that is used to regenerate this bundle.
*/


import { defineStore, type StoreDefinition } from "pinia";
import type { LCDClient } from '@cosmology/lcd';

export const useEndpoint: StoreDefinition<
    'pinia.endpoint',
    { restClient: LCDClient },
    {},
    { setRestClient(client: LCDClient): void }
> = defineStore('pinia.endpoint', {
    state: () => {
        return {
            restClient: {} as LCDClient,
        }
    },
    actions: {
        setRestClient(client: LCDClient) {
            this.restClient = client
        }
    }
})
